# Generated by Django 2.0.2 on 2018-03-06 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
