# Generated by Django 2.0.2 on 2018-03-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180305_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='loan_type',
            field=models.CharField(choices=[('SBA', 'SBA 7a'), ('SNR', 'Senior Secured'), ('JNR', 'Junior')], default='SBA', max_length=3),
            preserve_default=False,
        ),
    ]
