# Generated by Django 2.0.2 on 2018-03-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deal_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='industry_type',
            field=models.CharField(choices=[('TRK', 'Transport'), ('TEC', 'Tech'), ('PHR', 'Pharma')], default='TRK', max_length=3),
            preserve_default=False,
        ),
    ]
